<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>changePassword_datadriven_suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>fa46dd15-4e7c-4463-8d25-9960cbe125a2</testSuiteGuid>
   <testCaseLink>
      <guid>60bd70f3-9c6f-44ee-a74e-eede92ccf8d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/datadriven/csv/changePassword_datadriven_testcase</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4c5d6ca8-ecc0-4753-a355-43a6d214a1e0</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/datadriven/csv/changePassword_datadriven_csv</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>4c5d6ca8-ecc0-4753-a355-43a6d214a1e0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>curpwd</value>
         <variableId>a2083ec9-1e25-43be-ad66-cfaa2df6632c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4c5d6ca8-ecc0-4753-a355-43a6d214a1e0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>newpwd</value>
         <variableId>7eaa643a-03b1-46b1-b340-1fc17eb41a43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4c5d6ca8-ecc0-4753-a355-43a6d214a1e0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>newpwd1</value>
         <variableId>dcd77b13-5654-4fdb-909c-873431a9ed3e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
