<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>addchannel_datadriven_suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>618008dc-a753-41ef-aada-b0be83fbb550</testSuiteGuid>
   <testCaseLink>
      <guid>3de0bc25-23a0-4584-8caf-e259c2590673</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/addChannel_datadriven_testcase</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c2576daa-8df9-4942-b70d-0eaedfa827ef</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/addchannel_datadriven_csv</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>c2576daa-8df9-4942-b70d-0eaedfa827ef</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>name</value>
         <variableId>f6f1f0f3-064f-42b5-8c7d-9de9d115bf3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c2576daa-8df9-4942-b70d-0eaedfa827ef</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>opt1</value>
         <variableId>e90ae8da-04b1-4afe-8185-ceaf5bd6208e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c2576daa-8df9-4942-b70d-0eaedfa827ef</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>opt2</value>
         <variableId>a81000ed-e451-47df-944d-ff9b1f6acee2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
